# Generated by Django 5.1.1 on 2024-10-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_autor_livro_autores"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autores",
            new_name="autor",
        ),
    ]
