# Generated by Django 5.1.3 on 2024-12-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_autores_livro_autor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
    ]
