# Generated by Django 5.1.3 on 2025-02-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_compra_data_compra_tipo_pagamento_compra_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='quantidade',
            new_name='avaliacao',
        ),
    ]
