# Generated by Django 5.1.3 on 2025-02-06 02:16

import core.models.favorito
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_quantidade_favorito_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='avaliacao',
            field=models.IntegerField(validators=[core.models.favorito.validate_avaliacao]),
        ),
    ]
