# Generated by Django 5.1.3 on 2025-02-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_favorito_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
